Repository automl/auto-sklearn, pull requests merged in 2021-12, with the labels that each got.

#1238 Clearup warnings
  autosklearn/automl.py
  autosklearn/estimators.py
  autosklearn/metalearning/metafeatures/metafeatures.py
  autosklearn/metalearning/metalearning/meta_base.py
  autosklearn/metalearning/optimizers/metalearn_optimizer/metalearner.py
  autosklearn/metrics/__init__.py
  autosklearn/pipeline/components/base.py
  autosklearn/pipeline/components/data_preprocessing/categorical_encoding/encoding.py
  autosklearn/pipeline/components/data_preprocessing/imputation/categorical_imputation.py
  autosklearn/pipeline/components/data_preprocessing/rescaling/abstract_rescaling.py
  autosklearn/pipeline/components/feature_preprocessing/kitchen_sinks.py
  autosklearn/pipeline/components/regression/gaussian_process.py
  autosklearn/util/data.py
  examples/20_basic/example_multilabel_classification.py
  requirements.txt
  test/test_automl/test_estimators.py
  test/test_data/test_target_validator.py
  test/test_metalearning/pyMetaLearn/test_meta_features_sparse.py
  test/test_metric/test_metrics.py
  test/test_pipeline/components/classification/test_base.py
  test/test_pipeline/components/data_preprocessing/test_categorical_imputation.py
  test/test_pipeline/components/data_preprocessing/test_data_preprocessing_categorical.py
  test/test_pipeline/test_classification.py
  test/test_pipeline/test_regression.py
Labels: PR: Review Ready

#1325 Enable tests to be manually triggered
  .github/workflows/pytest.yml
Labels: PR: Review Ready

#1332 Update docstrings of `include` and `exclude` parameters of the estimators
  autosklearn/automl.py
  autosklearn/estimators.py
  autosklearn/smbo.py
Labels: PR: Review Ready, PR: Minor

#1260 added python 3.10 to versions
  .github/workflows/pytest.yml
Labels: PR: Review Ready, PR: Minor

#1339 Fixed dependancies warnings introduced by `sphinx_toolbox`
  doc/Makefile
  doc/conf.py
  setup.py
Labels: PR: Review Ready, PR: Minor

#1335 Fix regression algorithms to give correct output dimensions
  autosklearn/pipeline/components/regression/adaboost.py
  autosklearn/pipeline/components/regression/ard_regression.py
  autosklearn/pipeline/components/regression/decision_tree.py
  autosklearn/pipeline/components/regression/extra_trees.py
  autosklearn/pipeline/components/regression/gaussian_process.py
  autosklearn/pipeline/components/regression/gradient_boosting.py
  autosklearn/pipeline/components/regression/k_nearest_neighbors.py
  autosklearn/pipeline/components/regression/liblinear_svr.py
  autosklearn/pipeline/components/regression/libsvm_svr.py
  autosklearn/pipeline/components/regression/mlp.py
  autosklearn/pipeline/components/regression/random_forest.py
  autosklearn/pipeline/components/regression/sgd.py
  test/test_pipeline/components/regression/test_base.py
  test/test_pipeline/ignored_warnings.py
  test/test_pipeline/test_classification.py
  test/test_pipeline/test_regression.py
Labels: PR: Review Ready, PR: Minor

#1342 Update isort-check.yaml to remove occurences of black
  .github/workflows/isort_checker.yml
Labels: PR: Review Ready, PR: Minor

#1329 Fix random state not being used for sampling configurations
  autosklearn/util/pipeline.py
  test/test_metalearning/pyMetaLearn/test_meta_base.py
  test/test_metalearning/pyMetaLearn/test_metalearner.py
  test/test_pipeline/components/data_preprocessing/test_balancing.py
  test/test_pipeline/test_classification.py
Labels: PR: Review Ready, PR: Minor

#1338 Update warnings
  test/__init__.py
  test/test_automl/test_automl.py
  test/test_automl/test_estimators.py
  test/test_pipeline/components/classification/test_base.py
  test/test_pipeline/components/feature_preprocessing/test_liblinear.py
  test/test_pipeline/components/regression/test_base.py
  test/test_pipeline/ignored_warnings.py
  test/test_pipeline/test_classification.py
Labels: PR: Review Ready, PR: Minor

#1346 Update warnings
  test/__init__.py
  test/test_automl/test_automl.py
  test/test_automl/test_estimators.py
  test/test_pipeline/components/classification/test_base.py
  test/test_pipeline/components/feature_preprocessing/test_liblinear.py
  test/test_pipeline/components/regression/test_base.py
  test/test_pipeline/ignored_warnings.py
  test/test_pipeline/test_classification.py
Labels: PR: Review Ready, PR: Minor

#1341 Allow argument to specfiy how auto-sklearn handles compressing dataset size
  autosklearn/automl.py
  autosklearn/estimators.py
  autosklearn/experimental/askl2.py
  autosklearn/util/data.py
  doc/index.rst
  test/test_automl/test_automl.py
  test/test_automl/test_estimators.py
  test/test_util/test_data.py
Labels: PR: In progress, PR: Minor

#1321 Changes show_models() function to return a dictionary of models in ensemble
  autosklearn/automl.py
  autosklearn/estimators.py
  examples/20_basic/example_classification.py
  examples/20_basic/example_multilabel_classification.py
  examples/20_basic/example_multioutput_regression.py
  examples/20_basic/example_regression.py
  examples/40_advanced/example_get_pipeline_components.py
  examples/40_advanced/example_interpretable_models.py
  examples/60_search/example_random_search.py
  examples/60_search/example_sequential.py
  examples/60_search/example_successive_halving.py
  examples/80_extending/example_extending_classification.py
  examples/80_extending/example_extending_data_preprocessor.py
  examples/80_extending/example_extending_preprocessor.py
  examples/80_extending/example_extending_regression.py
  test/test_automl/test_estimators.py
Labels: PR: In progress, PR: Minor
